feat: prepare for v126

diff --git a/files/system/usr/libexec/ostools/loadingbar b/files/system/usr/libexec/ostools/loadingbar
--- a/files/system/usr/libexec/ostools/loadingbar
+++ b/files/system/usr/libexec/ostools/loadingbar
@@ -1,71 +1,187 @@
 #!/bin/bash
 
+clear_box=yes
 clear
 
-update_dimensions() {
-    term_width=$(tput cols)
-    term_height=$(tput lines)
-    bar_width=$((term_width * 70 / 100))
-    [[ $bar_width -gt $term_width ]] && bar_width=$term_width
+loading_message="Loading, please wait..."
+command_to_run=""
 
-    msg1=$1
-    msg2=$2
-    msg1_row=$((term_height / 2 - 1))
-    msg2_row=$((term_height / 2))
-    msg1_col=$(( (term_width - ${#msg1}) / 2 ))
-    msg2_col=$(( (term_width - ${#msg2}) / 2 ))
-
-    clear
-    tput cup $msg1_row $msg1_col
-    printf "%s" "$msg1"
-    tput cup $msg2_row $msg2_col
-    printf "%s" "$msg2"
-}
-
-tput civis
-trap "tput cnorm; clear; exit" EXIT
-update_dimensions "$1" "$2"
-trap 'update_dimensions "$1" "$2"' SIGWINCH
-
-offset=0
-frame=0
-frames_per_cycle=200
-
-if [[ -z "$3" ]]; then
-    echo "Error: No command provided to run in the background."
-    tput cnorm
-    exit 1
-fi
-
-if [[ "$4" == "--sysupdate-type" ]]; then
-    $3 & >> /tmp/update-logs.tmp 2>&1 &
-else
-    $3 &
-fi
-cmd_pid=$!
-
-while kill -0 $cmd_pid 2>/dev/null; do
-    tput cup 0 0
-    tput el
-
-    for ((i = 0; i < term_width; i++)); do
-        index=$(( (i - offset + term_width) % term_width ))
-        if (( index < bar_width )); then
-            printf "="
-        else
-            printf "#"
-        fi
-    done
-
-    angle=$(( (frame * 360 / frames_per_cycle) % 360 ))
-    rad=$(echo "$angle * 3.14159 / 180" | bc -l)
-    delay=$(echo "0.001 + (0.004 * (1 + s($rad)))" | bc -l)
-
-    sleep $delay
-
-    ((offset = (offset + 1) % term_width))
-    ((frame = (frame + 1) % frames_per_cycle))
+for arg in "$@"; do
+	if [[ "$arg" == --msg=* ]]; then
+		loading_message="${arg#--msg=}"
+	elif [[ "$arg" == --cmd=* ]]; then
+		command_to_run="${arg#--cmd=}"
+	fi
 done
 
-tput cnorm
-clear
+trap cleanup SIGINT SIGTERM SIGHUP SIGQUIT
+
+get_terminal_dimensions() {
+	height=$(tput lines)
+	width=$(tput cols)
+	echo "$height $width"
+}
+
+draw_box() {
+	local term_height="$1"
+	local term_width="$2"
+	local box_width=$((term_width * 3 / 4))
+	local box_height=3
+	local box_start_y=$(( (term_height - box_height) / 2 ))
+	local box_start_x=$(( (term_width - box_width) / 2 ))
+
+	tput cup "$box_start_y" "$box_start_x"
+
+	for ((i = 0; i < box_width; i++)); do
+		printf "#"
+	done
+	echo
+
+	tput cup "$((box_start_y + 1))" "$box_start_x"
+	printf "#"
+	tput cuf "$((box_width - 2))"
+	printf "#"
+	echo
+
+	tput cup "$((box_start_y + 2))" "$box_start_x"
+	for ((i = 0; i < box_width; i++)); do
+		printf "#"
+	done
+	echo
+}
+
+display_message() {
+	local term_height="$1"
+	local term_width="$2"
+	local box_width=$((term_width * 3 / 4))
+	local box_start_y=$(( (term_height - 3) / 2 ))
+	local box_start_x=$(( (term_width - box_width) / 2 ))
+	local message_y=$((box_start_y - 2))
+	local message_x=$(( (term_width - ${#loading_message}) / 2 ))
+
+	tput cup "$message_y" "$message_x"
+	printf "%s" "$loading_message"
+}
+
+clear_box_interior() {
+	local term_height="$1"
+	local term_width="$2"
+	local box_width=$((term_width * 3 / 4))
+	local box_height=3
+	local box_start_y=$(( (term_height - box_height) / 2 ))
+	local box_start_x=$(( (term_width - box_width) / 2 ))
+
+	tput cup "$((box_start_y + 1))" "$((box_start_x + 1))"
+
+	for ((i = 0; i < $((box_width - 2)); i++)); do
+		printf " "
+	done
+}
+
+draw_bar() {
+	local term_width="$1"
+	local box_width=$((term_width * 3 / 4))
+	local box_start_x=$(( (term_width - box_width) / 2 ))
+	local bar_width=$((term_width / 5))
+	local bar_y=$((box_start_y + 1))
+	local max_bar_offset=$((box_width - bar_width - 2))
+
+	tput cup "$bar_y" "$((box_start_x + 1 + old_bar_position))"
+	for ((i = 0; i < old_bar_width; i++)); do
+		printf " "
+	done
+
+	tput cup "$bar_y" "$((box_start_x + 1 + bar_position))"
+	for ((i = 0; i < bar_width; i++)); do
+		printf "-"
+	done
+
+	old_bar_position="$bar_position"
+	old_bar_width="$bar_width"
+}
+
+hide_cursor() {
+	tput civis
+}
+
+show_cursor() {
+	tput cnorm
+}
+
+cleanup() {
+	clear
+	show_cursor
+	exit 0
+}
+
+run_command() {
+	if [[ -n "$command_to_run" ]]; then
+		eval "$command_to_run" &
+		command_pid=$!
+		wait "$command_pid"
+		command_exit_code=$?
+		if [[ $command_exit_code -eq 0 ]]; then
+			kill -9 $$
+			cleanup
+		elif [[ $command_exit_code -ne 0 ]]; then
+			cleanup
+			echo "Error: Command failed with exit code $command_exit_code"
+			exit $command_exit_code
+		fi
+	fi
+}
+
+old_term_dimensions=""
+bar_position=0
+old_bar_position=0
+direction=1
+animation_speed=0.02
+
+hide_cursor
+
+initial_dimensions=$(get_terminal_dimensions)
+term_height=$(echo "$initial_dimensions" | awk '{print $1}')
+term_width=$(echo "$initial_dimensions" | awk '{print $2}')
+box_start_y=$(( (term_height - 3) / 2 ))
+
+draw_box "$term_height" "$term_width"
+display_message "$term_height" "$term_width"
+
+old_term_dimensions="$initial_dimensions"
+
+run_command &
+
+while true; do
+	current_dimensions=$(get_terminal_dimensions)
+
+	if [[ "$current_dimensions" != "$old_term_dimensions" ]]; then
+		clear
+		term_height=$(echo "$current_dimensions" | awk '{print $1}')
+		term_width=$(echo "$current_dimensions" | awk '{print $2}')
+		box_start_y=$(( (term_height - 3) / 2 ))
+		draw_box "$term_height" "$term_width"
+		display_message "$term_height" "$term_width"
+		old_term_dimensions="$current_dimensions"
+	fi
+
+	term_width=$(echo "$current_dimensions" | awk '{print $2}')
+	box_width=$((term_width * 3 / 4))
+	max_bar_offset=$((box_width - $((term_width / 5)) - 2))
+
+	draw_bar "$term_width"
+
+	if [[ "$clear_box" == "yes" ]]; then
+		clear_box_interior "$term_height" "$term_width"
+		unset clear_box
+	fi
+
+	bar_position=$((bar_position + direction))
+
+	if [[ "$bar_position" -le 0 ]]; then
+		direction=1
+	elif [[ "$bar_position" -ge "$max_bar_offset" ]]; then
+		direction=-1
+	fi
+
+	sleep $animation_speed
+done
