feat: ...im burnt out af

diff --git a/files/system/usr/libexec/ostools/update b/files/system/usr/libexec/ostools/update
--- a/files/system/usr/libexec/ostools/update
+++ b/files/system/usr/libexec/ostools/update
@@ -2,17 +2,41 @@
 
 set -euo pipefail
 
-loadingbar() {
-    /usr/libexec/ostools/loadingbar "$@"
-}
-
 if [[ "$EUID" -ne 0 ]]; then
     echo "Not authorized. Please run as root."
     exit 1
 fi
 
-if [[ "${1:-}" == "--no-interact" ]]; then
-    if [[ "${2:-}" == "--check-conditions" ]]; then
+throbber() {
+    /usr/libexec/ostools/throbber "$@"
+}
+
+no_interact=false
+check_conditions=false
+
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        --no-interact)
+            no_interact=true
+            shift
+            ;;
+        --check-conditions)
+            check_conditions=true
+            shift
+            ;;
+        --interactive)
+            no_interact=false
+            shift
+            ;;
+        *)
+            echo "Invalid argument: $1"
+            exit 1
+            ;;
+    esac
+done
+
+if $no_interact; then
+    if $check_conditions; then
         cpu_usage=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
         battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
         last_run_file="/etc/last_update_run"
@@ -45,19 +69,19 @@ if [[ "${1:-}" == "--no-interact" ]]; then
         echo "Done."
         exit 0
     fi
-elif [[ "${1:-}" == "--interactive" ]]; then
+elif ! $no_interact; then
     echo "Starting manual upgrade in 3 seconds."
     echo "Press CTRL+C to cancel."
     sleep 3
-    loadingbar --msg="Task: Update system" --cmd="bootc upgrade"
-    loadingbar --msg="Task: Update subsystem" --cmd="subsys pull --force"
-    loadingbar --msg="Task: Update system flatpaks" --cmd="flatpak upgrade --system"
+    throbber --msg="Task: Update system" --cmd="bootc upgrade"
+    throbber --msg="Task: Update subsystem" --cmd="subsys pull --force"
+    throbber --msg="Task: Update system flatpaks" --cmd="flatpak upgrade --system"
     for USER in /var/home/*; do
-        loadingbar --msg="Task: Update user flatpaks for $USER" --cmd="su - \"$USER\" -c \"flatpak upgrade --user\""
+        throbber --msg="Task: Update user flatpaks for $USER" --cmd="su - \"$USER\" -c \"flatpak upgrade --user\""
     done
-    loadingbar --msg="Task: Fetch Nix channels" --cmd="nix-channel --update"
-    loadingbar --msg="Task: Update Nix packages" --cmd="nix-env --upgrade"
-    loadingbar --msg="Task: Clean up" --cmd="nix-collect-garbage"
+    throbber --msg="Task: Fetch Nix channels" --cmd="nix-channel --update"
+    throbber --msg="Task: Update Nix packages" --cmd="nix-env --upgrade"
+    throbber --msg="Task: Clean up" --cmd="nix-collect-garbage"
     notify-send "System Update" "Task finished."
     echo "Update finished."
 else
diff --git a/files/system/usr/libexec/transit/setup-transit b/files/system/usr/libexec/transit/setup-transit
--- a/files/system/usr/libexec/transit/setup-transit
+++ b/files/system/usr/libexec/transit/setup-transit
@@ -4,7 +4,9 @@ set -oue pipefail
 
 if [[ -t 0 || -z "$(cat -)" ]]; then
     echo "Error: No input received." >&2
-    exit 1
+    exit 0
+elif [[ "$(id -u "$1")" -lt 1000 || ! grep -q "^$1:" /etc/passwd ]]; then
+    exit 0
 fi
 
 echo "Starting setup."
@@ -22,11 +24,7 @@ truncate -s $(df -h /var | tail -n 1 | awk '{print $2}') "$transit_dir"/repo/"$1
 
 echo "Associating image..."
 LOOPDEV=$(losetup -f --show "$transit_dir"/repo/"$1".homedir)
-
-if [[ -z "$LOOPDEV" ]]; then
-    echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir."
-    exit 1
-fi
+[[ -z "$LOOPDEV" ]] && echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir." && exit 1
 
 echo "Encrypting image..."
 echo "$pass" | cryptsetup --type luks2 --cipher aes-xts-plain64 luksFormat /dev/loop0
diff --git a/files/system/usr/libexec/transit/start-transit b/files/system/usr/libexec/transit/start-transit
--- a/files/system/usr/libexec/transit/start-transit
+++ b/files/system/usr/libexec/transit/start-transit
@@ -4,25 +4,19 @@ set -oue pipefail
 
 if [[ -t 0 || -z "$(cat -)" ]]; then
     echo "Error: No input received." >&2
-    exit 1
-fi
-
-pass=$(cat)
-transit_dir="/var/usrlocal/transit"
-
-if [[ "$(id -u "$1")" -lt 1000 ]]; then
+    exit 0
+elif [[ "$(id -u "$1")" -lt 1000 || ! grep -q "^$1:" /etc/passwd ]]; then
     exit 0
 elif [[ ! -f "$transit_dir"/repo/"$1".homedir ]]; then
     echo "$pass" | /usr/libexec/transit/setup-transit "$1"
 fi
 
+pass=$(cat)
+transit_dir="/var/usrlocal/transit"
+
 echo "Associating image..."
 LOOPDEV=$(losetup -f --show "$transit_dir"/repo/"$1".homedir)
-
-if [[ -z "$LOOPDEV" ]]; then
-    echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir."
-    exit 1
-fi
+[[ -z "$LOOPDEV" ]] && echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir." && exit 1
 
 echo "Decrypting image..."
 echo "$pass" | cryptsetup luksOpen "$LOOPDEV" in_transit-$(cat /etc/transit/transit-id)
diff --git a/files/system/usr/libexec/transit/stop-transit b/files/system/usr/libexec/transit/stop-transit
--- a/files/system/usr/libexec/transit/stop-transit
+++ b/files/system/usr/libexec/transit/stop-transit
@@ -5,16 +5,12 @@ shopt -s extglob
 
 transit_dir="/var/usrlocal/transit"
 
-if [[ "$(id -u "$1")" -lt 1000 || ! -f "$transit_dir"/repo/"$1".homedir ]]; then
+if [[ "$(id -u "$1")" -lt 1000 || ! -f "$transit_dir"/repo/"$1".homedir || ! grep -q "^$1:" /etc/passwd ]]; then
     exit 0
 fi
 
 LOOPDEV=$(losetup | grep "$transit_dir"/repo/"$1".homedir | cut -d':' -f1)
-
-if [[ -z "$LOOPDEV" ]]; then
-    echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir."
-    exit 1
-fi
+[[ -z "$LOOPDEV" ]] && echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir." && exit 1
 
 echo "Unmounting image..."
 umount /var/home
