feat: code cleanup

diff --git a/files/system/usr/bin/cherry b/files/system/usr/bin/cherry
--- a/files/system/usr/bin/cherry
+++ b/files/system/usr/bin/cherry
@@ -2,15 +2,13 @@
 
 set -oe pipefail
 
-# set variables
-CONTAINER_CONFIG_DIR="/etc/containerconf"
-USER_CONTAINER_CONFIG_DIR="$CONTAINER_CONFIG_DIR/$USER"
-CONTAINER_LIST_FILE="$CONTAINER_CONFIG_DIR/configs.d/.cherry/list.txt"
-CONTAINER_OVERRIDE_CONFIG="$HOME/.config/containerconf.d/override.conf"
-FILENAME_TMP=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 35 ; echo '')
-PS3="> "
+readonly CONTAINER_CONFIG_DIR="/etc/containerconf"
+readonly USER_CONTAINER_CONFIG_DIR="$CONTAINER_CONFIG_DIR/$USER"
+readonly CONTAINER_LIST_FILE="$CONTAINER_CONFIG_DIR/configs.d/.cherry/list.txt"
+readonly CONTAINER_OVERRIDE_CONFIG="$HOME/.config/containerconf.d/override.conf"
+readonly FILENAME_TMP=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 35 ; echo '')
+readonly PS3="> "
 
-# set functions
 help() {
     cat <<EOF 
 Usage: cherry <subcommand> [option]
@@ -64,18 +62,15 @@ EOF
 }
 
 status() {
-    if [[ -f /etc/transit_status ]]; then
-        local TRANSIT_STATUS=$(cat /etc/transit_status)
-    elif [[ ! -f /etc/transit_status ]]; then
-        local TRANSIT_STATUS="Not mounted"
-    fi
+    local TRANSIT_STATUS="Not mounted"
+    [[ -f /etc/transit_status ]] && TRANSIT_STATUS=$(cat /etc/transit_status)
     cat <<EOF
 bourbonOS $(cat /etc/bourbonOS_version)
 Pesticide: $(/usr/libexec/pesticide/status) | $(/usr/libexec/pesticide/version)
 Transit: $TRANSIT_STATUS | $(cat /etc/transit_version)
 =======================
 host: $(hostname)
-kargs: $(cat /proc/cmdline | sed -E 's/(ostree=)[^ ]+/\1.../' | sed -E 's/(BOOT_IMAGE=)[^ ]+/\1.../') | sed -E 's/(uuid=)[^ ]+/\1.../') | sed -E 's/(luks_uuid=)[^ ]+/\1.../')
+kargs: $(cat /proc/cmdline | sed -E 's/(ostree=)[^ ]+/\1.../' | sed -E 's/(BOOT_IMAGE=)[^ ]+/\1.../' | sed -E 's/(uuid=)[^ ]+/\1.../' | sed -E 's/(luks_uuid=)[^ ]+/\1.../')
 kernver: $(uname -r)
 =======================
 ostree status:
@@ -88,194 +83,92 @@ version() {
 }
 
 loadingbar() {
-    /usr/libexec/ostools/loadingbar $@
+    command -v /usr/libexec/ostools/loadingbar &>/dev/null && /usr/libexec/ostools/loadingbar "$@" || echo "Loading..."
 }
 
-# main function
+handle_baseos() {
+    case "$1" in
+        exec) shift; "$@" ;;
+        upgrade) clear; echo "Please authorize to start your system upgrade."; pkexec /usr/libexec/ostools/update --interactive ;;
+        status) status ;;
+        help | *) stem-help ;;
+    esac
+}
+
+handle_containeros() {
+    case "$1" in
+        new)
+            echo "Do you want to:"
+            select container in "Choose from a list of images" "Specify your own (advanced)"; do
+                case "$container" in
+                    "Choose from a list of images")
+                        echo "Select an image from the list:"
+                        select image in $(cat "$CONTAINER_LIST_FILE"); do
+                            [[ -n $image ]] && loadingbar --msg="Creating your container, this may take a second." --cmd="distrobox-assemble create --file /etc/containerconf/$image.ini" && echo "Done! You can switch to the container using 'cherry branch jump'." && exit 0
+                        done
+                        ;;
+                    "Specify your own (advanced)")
+                        read -p "Container URL/alias: " manual_container_url
+                        read -p "Container name: " manual_container_name
+                        cp /etc/containerconf/.ini-template "/tmp/$FILENAME_TMP.ini"
+                        sed -i "s/<name>/$manual_container_name/g" "/tmp/$FILENAME_TMP.ini"
+                        sed -i "s/<url>/$manual_container_url/g" "/tmp/$FILENAME_TMP.ini"
+                        nano "/tmp/$FILENAME_TMP.ini"
+                        loadingbar --msg="Creating your container, this may take a second." --cmd="distrobox-assemble create --file /tmp/$FILENAME_TMP.ini"
+                        rm "/tmp/$FILENAME_TMP.ini"
+                        echo "Done! You can switch to the container using 'cherry branch jump'."
+                        exit 0
+                        ;;
+                esac
+            done
+            ;;
+        rm)
+            containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
+            [[ -z $containers ]] && echo "No containers to remove." && exit 1
+            echo "Select a container by its number to remove it."
+            select container in $containers; do
+                [[ -n $container ]] && loadingbar --msg="Removing your container, this may take a second." --cmd="distrobox-rm $container" && echo "Removed $container." && exit 0
+            done
+            ;;
+        save)
+            containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
+            [[ -z $containers ]] && echo "No containers to save." && exit 1
+            echo "Select a container by its number to save it to an image."
+            select container in $containers; do
+                [[ -n $container ]] && loadingbar --msg="Saving your container as an image, this may take a second." --cmd="podman save $container $HOME/$container.tar" && echo "Container image saved at $HOME/$container.tar" && exit 0
+            done
+            ;;
+        load)
+            [[ ! -f "$2" ]] && echo "Error: Image path not found." && exit 1
+            loadingbar --msg="Loading your container image, this may take a second." --cmd="podman load $2"
+            echo "Container loaded from $2. You can switch to it using 'cherry branch jump'."
+            ;;
+        switch)
+            containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
+            [[ -z $containers ]] && echo "No containers to switch to." && exit 1
+            echo "Select a container by its number to switch to it."
+            select container in $containers; do
+                [[ -n $container ]] && exec distrobox-enter "$container"
+            done
+            ;;
+        list) distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$' ;;
+        help | *) branch-help ;;
+    esac
+}
+
+handle_fsguard() {
+    case "$1" in
+        status) /usr/libexec/pesticide/status ;;
+        check) /usr/libexec/pesticide/check ;;
+        apply) shift; /usr/libexec/pesticide/enroll "$@" ;;
+        help | *) pesticide-help ;;
+    esac
+}
+
 case "$1" in
-    baseos)
-        shift
-        case "$1" in
-            exec)
-                shift
-                $@
-                ;;
-            upgrade)
-                clear
-                echo "Please authorize to start your system upgrade."
-                pkexec /usr/libexec/ostools/update --interactive
-                ;;
-            status)
-                status
-                ;;
-            help)
-                stem-help
-                ;;
-            *)
-                stem-help
-                exit 1
-                ;;
-        esac
-        ;;
-    containeros)
-        shift
-        case "$1" in
-            "new")
-                echo "Do you want to:"
-                select container in "Choose from a list of images" "Specify your own (advanced)"; do
-                    if [[ -n $container ]]; then
-                        case "$container" in
-                            "Choose from a list of images")
-                                echo "Select an image from the list:"
-                                select image in $(cat /etc/containerconf/.cherry/list.txt); do
-                                    if [[ -n $image ]]; then
-                                        loadingbar --msg="Creating your container, this may take a second." --cmd="distrobox-assemble create --file /etc/containerconf/$image.ini"
-                                        echo "Done! You can switch to the container using 'cherry branch jump'."
-                                        exit 0
-                                    else
-                                        echo "Invalid selection."
-                                        exit 1
-                                    fi
-                                done
-                                ;;
-                            "Specify your own (advanced)")
-                                read -p "Container URL/alias: " manual_container_url
-                                read -p "Container name: " manual_container_name
-                                echo "An editor will open to allow you to specify additional options."
-                                echo "If you do not know how to specify additional options in the editor,"
-                                echo "Please type the word help and press enter."
-                                echo "When you're done looking at the help file, press q to exit."
-                                echo "Then, reselect 'Specify your own (advanced)' to continue."
-                                echo "If you don't need help, just press enter."
-                                read -p "> " container_help_var
-                                if [[ "$container_help_var" == "help" ]]; then
-                                    less /etc/containerconf/.cherry/editor-syntax.txt
-                                    new_container
-                                else
-                                    cp /etc/containerconf/.ini-template "/tmp/$FILENAME_TMP.ini"
-                                    sed -i "s/<name>/$manual_container_name/g" "/tmp/$FILENAME_TMP.ini"
-                                    sed -i "s/<url>/$manual_container_url/g" "/tmp/$FILENAME_TMP.ini"
-                                    nano "/tmp/$FILENAME_TMP.ini"
-                                    loadingbar --msg="Creating your container, this may take a second." --cmd="distrobox-assemble create --file "/tmp/$FILENAME_TMP.ini""
-                                    rm "/tmp/$FILENAME_TMP.ini"
-                                fi
-                                echo "Done! You can switch to the container using 'cherry branch jump'."
-                                exit 0
-                                ;;
-                            *)
-                                echo "Invalid choice."
-                                exit 1
-                                ;;
-                        esac
-                    fi
-                done
-                ;;
-            "rm")
-                if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
-                    echo "No containers to remove."
-                    exit 1
-                else
-                    echo "Select a container by its number to remove it."
-                    select container in $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'); do
-                        if [[ -n $container ]]; then
-                            loadingbar --msg="Removing your container, this may take a second." --cmd="distrobox-rm "$container""
-                            echo "Removed $container."
-                            exit 0
-                        else
-                            echo "Invalid selection."
-                            exit 1
-                        fi
-                    done
-                fi
-                ;;
-            "save")
-                if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
-                    echo "No containers to save."
-                    exit 1
-                else
-                    echo "Select a container by its number to save it to an image."
-                    select container in $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'); do
-                        if [[ -n $container ]]; then
-                            loadingbar --msg="Saving your container as an image, this may take a second." --cmd="podman save "$container" "$HOME/$container.tar""
-                            echo "Container image saved at $HOME/$container.tar"
-                            exit 0
-                        else
-                            echo "Invalid selection."
-                            exit 1
-                        fi
-                    done
-                fi
-                ;;
-            "load")
-                shift
-                if [[ ! -f "$1" ]]; then
-                    echo "Error: Image path not found."
-                    exit 1
-                fi
-                loadingbar --msg="Loading your container image, this may take a second." --cmd="podman load "$1""
-                echo "Container loaded from $1. You can switch to it using 'cherry branch jump'."
-                ;;
-            "switch")
-                if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
-                    echo "No containers to switch to."
-                    exit 1
-                else
-                    echo "Select a container by its number to switch to it."
-                    select container in $(distrobox-list | awk '{print $3}' | grep -v '^NAME$' | sed 's/^cherry-cli$/default container/'); do
-                        if [[ -n $container ]]; then
-                            clear
-                            printf "Switching to container $container...\n\n"
-                            exec distrobox-enter "$container"
-                        else
-                            echo "Invalid selection."
-                            exit 1
-                        fi
-                    done
-                fi
-                ;;
-            "list")
-                distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'
-                ;;
-            "help")
-                branch-help
-                ;;
-            *)
-                echo "Error: Invalid option."
-                branch-help
-                exit 1
-                ;;
-        esac
-        ;;
-    fsguard)
-        shift
-        case "$1" in
-            status)
-                /usr/libexec/pesticide/status
-                ;;
-            check)
-                /usr/libexec/pesticide/check
-                ;;
-            apply)
-                shift
-                /usr/libexec/pesticide/enroll "$@"
-                ;;
-            help)
-                pesticide-help
-                ;;
-            *)
-                pesticide-help
-                exit 1
-                ;;
-        esac
-        ;;
-    version)
-        version
-        ;;
-    help)
-        help
-        ;;
-    *)
-        help
-        exit 1
-        ;;
+    baseos) shift; handle_baseos "$@" ;;
+    containeros) shift; handle_containeros "$@" ;;
+    fsguard) shift; handle_fsguard "$@" ;;
+    version) version ;;
+    help | *) help ;;
 esac
diff --git a/files/system/usr/libexec/transit/stop-transit b/files/system/usr/libexec/transit/stop-transit
--- a/files/system/usr/libexec/transit/stop-transit
+++ b/files/system/usr/libexec/transit/stop-transit
@@ -3,16 +3,33 @@
 set -oue pipefail
 shopt -s extglob
 
-[[ "$(id -u $1)" -lt 1000 || "$1" == "root" ]]; exit 0
-[[ ! -d /var/home/$1 ]]; mkhomedir_helper $1
-[[ ! -f /var/usrlocal/transit/repo/$1.homedir ]]; cat | /usr/libexec/transit/setup-transit $1; exit 0
+if [[ "$(id -u "$1")" -lt 1000 || "$1" == "root" ]]; then
+    exit 0
+fi
+
+if [[ ! -d /var/home/"$1" ]]; then
+    mkhomedir_helper "$1"
+fi
+
+if [[ ! -f /var/usrlocal/transit/repo/"$1".homedir ]]; then
+    cat | /usr/libexec/transit/setup-transit "$1"
+    exit 0
+fi
+
+LOOPDEV=$(losetup | grep /var/usrlocal/transit/repo/"$1".homedir | cut -d':' -f1)
+
+if [[ -z "$LOOPDEV" ]]; then
+    echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
+    exit 1
+fi
 
 echo "Unmounting..."
-
-umount /var/home/$1
+umount /var/home/"$1"
 cryptsetup luksClose in_transit-$(cat /etc/transit-id)
-losetup -d /dev/loop0
-rm -rf /var/usrlocal/transit/main/.work/*
+losetup -d "$LOOPDEV"
 
+echo "Cleaning up..."
+rm -rf /var/usrlocal/transit/main/.work/*
 rm /etc/transit_status
+
 echo "Unmounted /var/home/$1."
