fix: reorder setup logic + add passwd check

diff --git a/files/system/usr/libexec/transit/setup-transit b/files/system/usr/libexec/transit/setup-transit
--- a/files/system/usr/libexec/transit/setup-transit
+++ b/files/system/usr/libexec/transit/setup-transit
@@ -2,6 +2,11 @@
 
 set -oue pipefail
 
+if [[ -t 0 || -z "$(cat -)" ]]; then
+    echo "Error: No input received." >&2
+    exit 1
+fi
+
 echo "Starting setup."
 pass=$(cat)
 set_readme="false"
@@ -11,17 +16,16 @@ if [[ -d /var/home/"$1"/Desktop ]]; then
     set_readme="true"
 fi
 
-echo "Associating device..."
+echo "Creating image..."
+truncate -s $(df -h /var | tail -n 1 | awk '{print $2}') /var/usrlocal/transit/repo/"$1".homedir
+
+echo "Associating image..."
 LOOPDEV=$(losetup -f --show /var/usrlocal/transit/repo/"$1".homedir)
 
 if [[ -z "$LOOPDEV" ]]; then
     echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
     exit 1
 fi
-
-echo "Creating image..."
-truncate -s $(df -h /var/ | tail -n 1 | awk '{print $2}') /var/usrlocal/transit/repo/"$1".homedir
-losetup "$LOOPDEV" /var/usrlocal/transit/repo/"$1".homedir
 
 echo "Encrypting image..."
 echo "$pass" | cryptsetup --type luks2 --cipher aes-xts-plain64 luksFormat /dev/loop0
@@ -31,12 +35,12 @@ unset pass
 echo "Formatting image..."
 mkfs.ext4 -F /dev/mapper/init_transit-"$(cat /etc/transit/transit-id)"
 
-echo "Mounting and preparing..."
+echo "Mounting and preparing image..."
 mount /dev/mapper/init_transit-"$(cat /etc/transit/transit-id)" /var/home
 mkhomedir_helper "$1"
 [[ "$set_readme" == "true" ]] && cp /etc/transit/.README.md /var/home/"$1"/README.md
 
-echo "Unmounting..."
+echo "Unmounting image..."
 umount /var/home
 
 echo "Cleaning up..."
diff --git a/files/system/usr/libexec/transit/start-transit b/files/system/usr/libexec/transit/start-transit
--- a/files/system/usr/libexec/transit/start-transit
+++ b/files/system/usr/libexec/transit/start-transit
@@ -2,15 +2,20 @@
 
 set -oue pipefail
 
+if [[ -t 0 || -z "$(cat -)" ]]; then
+    echo "Error: No input received." >&2
+    exit 1
+fi
+
 pass=$(cat)
 
-if [[ "$(id -u "$1")" -lt 1000 || "$1" == "root" ]]; then
+if [[ "$(id -u "$1")" -lt 1000 ]]; then
     exit 0
 elif [[ ! -f /var/usrlocal/transit/repo/"$1".homedir ]]; then
     echo "$pass" | /usr/libexec/transit/setup-transit "$1"
 fi
 
-echo "Associating device..."
+echo "Associating image..."
 LOOPDEV=$(losetup -f --show /var/usrlocal/transit/repo/"$1".homedir)
 
 if [[ -z "$LOOPDEV" ]]; then
@@ -18,13 +23,14 @@ if [[ -z "$LOOPDEV" ]]; then
     exit 1
 fi
 
-echo "Decrypting..."
+echo "Decrypting image..."
 echo "$pass" | cryptsetup luksOpen "$LOOPDEV" in_transit-$(cat /etc/transit/transit-id)
 
 unset pass
 
-echo "Mounting..."
+echo "Mounting image..."
 mount --bind -o ro /var/home /var/usrlocal/transit/varhome
 mount /dev/mapper/in_transit-$(cat /etc/transit/transit-id) /var/home
 
-echo "Mounted at /var/home/$1." | tee /etc/transit/transit-status
+echo "Mounted image successfully."
+echo "MOUNTED" > /etc/transit/transit-status
