fix: add LOOPDEV detection

diff --git a/files/system/usr/libexec/transit/setup-transit b/files/system/usr/libexec/transit/setup-transit
--- a/files/system/usr/libexec/transit/setup-transit
+++ b/files/system/usr/libexec/transit/setup-transit
@@ -3,6 +3,7 @@
 set -oue pipefail
 
 echo "Starting setup."
+pass=$(cat)
 
 if [[ -d /var/home/"$1"/Desktop ]]; then
     echo "Initialized homedir detected."
@@ -18,14 +19,21 @@ EOF > /var/home/"$1"/README.md
     echo "Done."
 fi
 
+echo "Associating device..."
+LOOPDEV=$(losetup -f --show /var/usrlocal/transit/repo/"$1".homedir)
+
+if [[ -z "$LOOPDEV" ]]; then
+    echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
+    exit 1
+fi
+
 echo "Creating image..."
 truncate -s $(df -h /var/ | tail -n 1 | awk '{print $2}') /var/usrlocal/transit/repo/"$1".homedir
-losetup /dev/loop0 /var/usrlocal/transit/repo/$1.homedir
+losetup $LOOPDEV /var/usrlocal/transit/repo/$1.homedir
 
 echo "Encrypting image..."
-pass=$(cat)
 echo "$pass" | cryptsetup --type luks2 --cipher aes-xts-plain64 luksFormat /dev/loop0
-echo "$pass" | cryptsetup luksOpen /dev/loop0 init_transit-$(cat /etc/transit-id)
+echo "$pass" | cryptsetup luksOpen $LOOPDEV init_transit-$(cat /etc/transit-id)
 unset pass
 
 echo "Formatting image..."
@@ -33,6 +41,6 @@ mkfs.ext4 -F /dev/mapper/init_transit-$(cat /etc/transit-id)
 
 echo "Cleaning up..."
 cryptsetup luksClose init_transit-$(cat /etc/transit-id)
-losetup -d /dev/loop0
+losetup -d $LOOPDEV
 
 echo "Setup finished."
diff --git a/files/system/usr/libexec/transit/start-transit b/files/system/usr/libexec/transit/start-transit
--- a/files/system/usr/libexec/transit/start-transit
+++ b/files/system/usr/libexec/transit/start-transit
@@ -19,6 +19,11 @@ fi
 echo "Associating device..."
 LOOPDEV=$(losetup -f --show /var/usrlocal/transit/repo/"$1".homedir)
 
+if [[ -z "$LOOPDEV" ]]; then
+    echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
+    exit 1
+fi
+
 echo "Decrypting..."
 echo "$pass" | cryptsetup luksOpen "$LOOPDEV" in_transit-$(cat /etc/transit-id)
 
